//
// Created by Muaz Moin on 22/04/2024.
//

#ifndef PROJECTTITLE_CLIMATECOMPENSATIONINITIATIVE_H
#define PROJECTTITLE_CLIMATECOMPENSATIONINITIATIVE_H

#endif //PROJECTTITLE_CLIMATECOMPENSATIONINITIATIVE_H
